[versions]
kotlin = "2.1.21"
kotlin-logging = "7.0.7"
ktor3 = "3.0.3"
logback = "1.5.13"
lsp4j = "0.24.0"
slf4j = "2.0.17"
testcontainers = "1.19.7"
code = "1.0.0-beta.91"

[libraries]
eclipse-lsp4 = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4j" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging"}
code-features = { module = "ai.jetbrains.code.features:code-features-common-cli", version.ref = "code" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor3" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor3" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor3" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor3" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }